import SwiftUI
import Combine

// The built-in droplets and their defaults.

extension AppState {
    // MARK: - Default Data
    func loadDefaultDroplets() {
        droplets = Self.defaultDroplets
    }

    /// Every built-in droplet with its shipped on/off state. Static, so
    /// settings keys (per-widget shortcuts) can be listed without an instance.
    nonisolated static let defaultDroplets: [DropletModel] = [
        DropletModel(id: "systemStats", name: "System Stats", tag: "Live CPU, RAM & Battery", category: .productivity, iconSystemName: "cpu", summary: "Monitor live CPU usage, memory pressure, and battery life directly in your Dynamic Island.", isEnabled: true),
        DropletModel(id: "caffeine", name: "High Alert", tag: "Keeps your Mac awake", category: .productivity, iconSystemName: "cup.and.saucer.fill", summary: "Prevent your Mac from sleeping during downloads, backups, or presentations.", isEnabled: true),
        DropletModel(id: "timer", name: "Timer", tag: "Countdown & stopwatch", category: .productivity, iconSystemName: "hourglass", summary: "A countdown timer and a stopwatch with laps. The time stays in the notch while it runs.", isEnabled: true, isNew: true),
        DropletModel(id: "pomodoro", name: "Pomodoro", tag: "Focus sessions in the notch", category: .productivity, iconSystemName: "timer", summary: "Stay in the flow state with structured work and break intervals in the notch.", isEnabled: true),
        DropletModel(id: "scratchpad", name: "Notes", tag: "Quick notes that live in your notch", category: .productivity, iconSystemName: "note.text", summary: "Multiple rich-text notes in the notch, with bold, headings and lists, pinning, and an optional two-way sync with Apple Notes.", isEnabled: true),
        DropletModel(id: "calculator", name: "Quick Math", tag: "Instant expression solver", category: .productivity, iconSystemName: "function", summary: "Evaluate math expressions instantly from your Dynamic Island.", isEnabled: true),
        DropletModel(id: "aiCutout", name: "Cutout", tag: "On-device image segmentation", category: .ai, iconSystemName: "person.crop.circle.badge.checkmark", summary: "Isolate subjects and remove photo backgrounds with private local AI.", isEnabled: true, isNew: true),
        DropletModel(id: "colorPicker", name: "Color Dropper", tag: "Screen pixel color sampler", category: .productivity, iconSystemName: "eyedropper.halffull", summary: "Pick any color on your display and copy its Hex code immediately.", isEnabled: true),
        DropletModel(id: "converter", name: "Quick Convert", tag: "Fast format transcoder", category: .productivity, iconSystemName: "arrow.triangle.2.circlepath", summary: "Convert images, videos, and documents into PNG, JPEG, WebP, GIF or PDF directly in your notch.", isEnabled: true, isNew: true),
        DropletModel(id: "windowSnapper", name: "Window Snap", tag: "Screen tile & layouts", category: .productivity, iconSystemName: "rectangle.split.2x1", summary: "Tile and organize your windows into halves, thirds, or fullscreen directly from the notch.", isEnabled: true, isNew: true),
        DropletModel(id: "snipper", name: "Element Capture", tag: "Screenshots & OCR", category: .productivity, iconSystemName: "camera.viewfinder", summary: "Capture selected screen regions or windows and hold them in the Tray with built-in OCR text extraction.", isEnabled: true, isNew: true),
        DropletModel(id: "termiNotch", name: "TermiNotch", tag: "Full terminal emulation in the notch", category: .productivity, iconSystemName: "apple.terminal", summary: "A real shell in your notch: colours, Ctrl-C, tabs and programs like vim or top, in an expanded full-shelf terminal or a quick command bar. Open the folder in Terminal, iTerm, Ghostty or Warp.", isEnabled: true),
        DropletModel(id: "thunderstorm", name: "Thunderstorm", tag: "Mac search with file actions", category: .productivity, iconSystemName: "bolt.fill", summary: "Search your Mac with Spotlight and open, reveal, Quick Look or send results to the Tray.", isEnabled: true, isNew: true),
        DropletModel(id: "ring", name: "Ring", tag: "Radial actions at your cursor", category: .productivity, iconSystemName: "circle.circle", summary: "A radial menu that opens at the pointer with a shortcut, for your most-used Tama actions.", isEnabled: true, isNew: true),
        DropletModel(id: "ocr", name: "OCR", tag: "Text from images & PDFs", category: .ai, iconSystemName: "text.viewfinder", summary: "Extract text from images and PDFs on-device with Apple Vision.", isEnabled: true, isNew: true),
        DropletModel(id: "voiceTranscribe", name: "Voice Transcribe", tag: "Record & transcribe on-device", category: .ai, iconSystemName: "waveform.badge.mic", summary: "Record voice notes and turn speech into text with on-device recognition.", isEnabled: true, isNew: true),
        DropletModel(id: "audioControl", name: "Audio Control", tag: "Per-app volume", category: .productivity, iconSystemName: "slider.vertical.3", summary: "Set the volume of each app that is playing sound, separately.", isEnabled: true, isNew: true),
        DropletModel(id: "obsidian", name: "Obsidian", tag: "Your vault, live on the shelf", category: .productivity, iconSystemName: "diamond.fill", summary: "Browse and edit your vault's notes in the notch, newest first, and append quick notes, clips and links to today's daily note or an inbox.", isEnabled: true, isNew: true),
        DropletModel(id: "liquidMouse", name: "LiquidMouse", tag: "Smooth mouse scrolling", category: .productivity, iconSystemName: "computermouse.fill", summary: "Smooth scrolling for an external mouse wheel, and a scroll direction of its own.", isEnabled: true, isNew: true),
        DropletModel(id: "meetings", name: "Meetings", tag: "Call HUD, mute, camera & hang up", category: .productivity, iconSystemName: "video.fill", summary: "Detects calls in Zoom, Google Meet, Teams, Webex, Slack, WhatsApp and FaceTime. Shows a call timer with your live mic level in the notch, pauses music for the call, and mutes the mic for every app, toggles the camera, shares or hangs up — with a quick task field and meeting notes mid-call.", isEnabled: true, isNew: true),
        DropletModel(id: "notifications", name: "Notification HUD", tag: "Surface incoming notifications in the notch", category: .productivity, iconSystemName: "bell.badge.fill", summary: "Mirrors your Mac's notifications in the notch with the real app icon, per-app filtering, a recent list and quick reply to iMessage. Reads the macOS notification store, which needs Full Disk Access.", isEnabled: false, isNew: true),
        DropletModel(id: "agents", name: "Agents", tag: "Live Claude, Codex & Cursor progress", category: .ai, iconSystemName: "sparkles", summary: "See what Claude Code, Codex and Cursor are doing: a glyph and spinner in the notch while an agent works, and a card with its task, the command it runs and its latest reply.", isEnabled: false, isNew: true),
        DropletModel(id: "notchface", name: "Notchface", tag: "Live notch camera preview", category: .media, iconSystemName: "web.camera", summary: "A mirror in your notch: a live preview from the camera you pick, to check your hair before a call. The camera stays off until you start it.", isEnabled: true, isNew: true),
        DropletModel(id: "appleMusic", name: "Apple Music", tag: "Native controls for Apple Music", category: .media, iconSystemName: "music.note", summary: "Use native Apple Music controls in Tama so playback stays accessible while you work. You can handle transport actions without bouncing between windows.", isEnabled: true, isNew: true),
        DropletModel(id: "weather", name: "Weather", tag: "Live weather widget", category: .media, iconSystemName: "cloud.sun.fill", summary: "Current conditions, today's high and low and the next hours for where you are or a city you pick, from Open-Meteo.", isEnabled: true, isNew: true),
        DropletModel(id: "mechey", name: "Mechey", tag: "Mechanical keyboard sounds", category: .productivity, iconSystemName: "keyboard.fill", summary: "Play satisfying mechanical switch sounds as you type.", isEnabled: false, isNew: true),
        DropletModel(id: "localSend", name: "LocalSend", tag: "AirDrop for every device, no cloud", category: .productivity, iconSystemName: "dot.radiowaves.left.and.right", summary: "AirDrop-style sharing with any device over the LocalSend protocol. Send files from the Tray, the Basket or a Quick Action tile to phones, Windows and Linux PCs and other Macs running LocalSend on the same network, and receive from them with a prompt, an optional PIN and a folder of your choice. Transfers stay on your network, encrypted with HTTPS.", isEnabled: false, isNew: true),
        DropletModel(id: "menuBar", name: "Menu Bar Manager", tag: "Hide menu bar icons behind a chevron", category: .productivity, iconSystemName: "menubar.rectangle", summary: "Clean up your menu bar: ⌘-drag icons to the left of Tama's divider and they fold away behind a chevron. Click the chevron to show or hide them, with an optional always-hidden section. Runs inside Tama — nothing to install.", isEnabled: false, isNew: true),
    ]
}
